dryrun_enabled: true
environment_type: PRODUCTION
iam_role: arn:aws:iam::962390577453:role/service-role/a206448-cicd-cicd-pipeline-swaraj-deploy
notification_emails:
- swarajsampad.mallick@thomsonreuters.com
stage_order:
- infra
